## $f(x) = x^n$.

## First Order Derivative $f'(x) = nx^{n-1}$



In [ ]:
import tensorflow as tf
a = tf.constant(6.0)
with tf.GradientTape() as t:
  t.watch(a)
  y=a*a
dy=t.gradient(y,a)
dy


<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

## First Order derivatve of sigmoid and Tanh using gradient tape

#### sigmoid $f(x) = \frac{1}{1 + e^{-x}}$
#### Tanh $f(x) = \frac{2}{1 + e ^{-2x}} -1$

In [ ]:
# sigmoid

x=tf.constant([2.0])

with tf.GradientTape() as t:
  t.watch(x)
  y = tf.divide(1.0,(tf.add(1.0,tf.exp(-x))))
dy=t.gradient(y,x)
dy

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.10499357], dtype=float32)>

In [ ]:
# Tanh
x=tf.constant([2.0])
with tf.GradientTape() as t:
  t.watch(x)
  y = tf.subtract(tf.divide(2.0,tf.add(1.0,tf.exp(tf.multiply(-2.0,x)))),1.0)
dy=t.gradient(y,x)
dy

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.07065082], dtype=float32)>

## Linear Regression

In [ ]:
num_example=100
batch_size=8
epoch=10

inputs = tf.random.normal(shape=[num_example])

w = tf.Variable(tf.random.uniform(shape=[batch_size]))
b = tf.Variable(tf.random.uniform(shape=[batch_size]))

outputs = tf.random.normal(shape=[num_example])

optimizer = tf.optimizers.Adam(0.001)
loss=tf.keras.losses.MeanSquaredError(reduction=
                                      tf.keras.losses.Reduction.NONE)

dataset = tf.data.Dataset.from_tensor_slices((inputs, outputs))
dataset = dataset.shuffle(buffer_size=1024).batch(batch_size,
                                                  drop_remainder=True)

def model(x):
  return tf.add(tf.multiply(w,x),b)


def train_step(inputs,outputs):
  with tf.GradientTape() as t:
    y_output = model(inputs)
    loss_val = loss(outputs,y_output)
    print(loss_val)
    grads = t.gradient(loss_val,[b,w])
    optimizer.apply_gradients(zip(grads,[b,w]))


def main():
  for i in range(epoch):
    print("Epochs ",i+1)
    for j,(feature,label) in enumerate(dataset):
      train_step(feature,label)


if __name__=='__main__':
  main()

Epochs  1
tf.Tensor(0.5926085, shape=(), dtype=float32)
tf.Tensor(1.0550075, shape=(), dtype=float32)
tf.Tensor(2.2075531, shape=(), dtype=float32)
tf.Tensor(2.7672424, shape=(), dtype=float32)
tf.Tensor(1.8412142, shape=(), dtype=float32)
tf.Tensor(2.5739684, shape=(), dtype=float32)
tf.Tensor(2.1910534, shape=(), dtype=float32)
tf.Tensor(2.9459448, shape=(), dtype=float32)
tf.Tensor(1.1921713, shape=(), dtype=float32)
tf.Tensor(1.2546576, shape=(), dtype=float32)
tf.Tensor(2.0187178, shape=(), dtype=float32)
tf.Tensor(1.5747628, shape=(), dtype=float32)
Epochs  2
tf.Tensor(2.2077312, shape=(), dtype=float32)
tf.Tensor(1.0533657, shape=(), dtype=float32)
tf.Tensor(0.86177754, shape=(), dtype=float32)
tf.Tensor(1.6410985, shape=(), dtype=float32)
tf.Tensor(1.4750881, shape=(), dtype=float32)
tf.Tensor(3.1038613, shape=(), dtype=float32)
tf.Tensor(1.5539604, shape=(), dtype=float32)
tf.Tensor(1.6509082, shape=(), dtype=float32)
tf.Tensor(2.6341617, shape=(), dtype=float32)
tf.Tensor(0.8